### ISSUE TITLE
Koji produces an error if used for the first commit after initialization

### ISSUE THREAD

**Issue by tkapias** [cococonscious/koji#104]
**Describe the bug**

I get an error if I try to use koji for the first commit after the creation of a new repository.

Using `git commit -m ''` works, and then kojo works too for the next ones.

**To Reproduce**

``` bash
git init test/
cd test
touch testfile
git add testfile 
koji
```

``` bash
Error: reference 'refs/heads/master' not found; class=Reference (4)
```

``` bash
git commit -m 'init'
touch testfile2
git add testfile2
koji
```

```
❯ feat:       ✨ A new feature
  fix:        🐛 A bug fix
  docs:       📚 Documentation only changes
  style:      💄 Changes that do not affect the meaning of the code
  refactor:   🔨 A code change that neither fixes a bug nor adds a feature
  perf:       ⚡ A code change that improves performance
  test:       🚨 Adding missing tests or correcting existing tests
(Move up and down to reveal more choices
```

**Expected behavior**

Koji should have been able to produce the first commit.

**Additional context**

- git version 2.45.2
- koji 2.2.0
- GNU bash, version 5.2.32(1)-release (x86_64-pc-linux-gnu)

**Comment by cococonscious** [comment]
Hi Tomasz, thanks for raising this issue! It seemed to be a problem with the autocomplete functionality and will be fixed with #105 which will be included in the next release (#95). 
In the meantime, disable autocomplete through its configuration parameter or install koji directly from the repository as soon as #105 is merged (`cargo install --git https://github.com/cococonscious/koji`)
